// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// parallel //
// -------- //

#define parallel_wrap_target 2
#define parallel_wrap 8
#define parallel_pio_version 1

static const uint16_t parallel_program_instructions[] = {
    0xa02b, //  0: mov    x, ~null
    0x2080, //  1: wait   1 gpio, 0
            //     .wrap_target
    0xf080, //  2: set    pindirs, 0      side 0
    0x2001, //  3: wait   0 gpio, 1
    0x00c3, //  4: jmp    pin, 3
    0x8080, //  5: pull   noblock
    0x6008, //  6: out    pins, 8
    0xfe9f, //  7: set    pindirs, 31     side 7
    0x208c, //  8: wait   1 gpio, 12
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program parallel_program = {
    .instructions = parallel_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = parallel_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config parallel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + parallel_wrap_target, offset + parallel_wrap);
    sm_config_set_sideset(&c, 4, true, true);
    return c;
}
#endif

